[project]
name = "uart-spartan-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.31",
    "opencv-python>=4.12.0.88",
    "pyserial>=3.5",
]
